/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 25/04/2022 10:34:04
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     150000000
#define MX_SYSCLKFreq_VALUE                     150000000
#define MX_HCLKFreq_Value                       150000000
#define MX_FCLKCortexFreq_Value                 150000000
#define MX_CortexFreq_Value                     150000000
#define MX_AHBFreq_Value                        150000000
#define MX_APB1Freq_Value                       37500000
#define MX_APB2Freq_Value                       75000000
#define MX_APB1TimFreq_Value                    75000000
#define MX_APB2TimFreq_Value                    150000000
#define MX_48MHZClocksFreq_Value                42857142
#define MX_EthernetFreq_Value                   150000000
#define MX_I2SClocksFreq_Value                  200000000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    150000000

/*-------------------------------- CAN1       --------------------------------*/

#define MX_CAN1                                 1

/* GPIO Configuration */

/* Pin PA11 */
#define MX_CAN1_RX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_RX_Pin                          PA11
#define MX_CAN1_RX_GPIOx                        GPIOA
#define MX_CAN1_RX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN1_RX_GPIO_Pin                     GPIO_PIN_11
#define MX_CAN1_RX_GPIO_AF                      GPIO_AF9_CAN1
#define MX_CAN1_RX_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PA12 */
#define MX_CAN1_TX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN1_TX_Pin                          PA12
#define MX_CAN1_TX_GPIOx                        GPIOA
#define MX_CAN1_TX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN1_TX_GPIO_Pin                     GPIO_PIN_12
#define MX_CAN1_TX_GPIO_AF                      GPIO_AF9_CAN1
#define MX_CAN1_TX_GPIO_Mode                    GPIO_MODE_AF_PP

/*-------------------------------- CAN2       --------------------------------*/

#define MX_CAN2                                 1

/* GPIO Configuration */

/* Pin PB5 */
#define MX_CAN2_RX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN2_RX_Pin                          PB5
#define MX_CAN2_RX_GPIOx                        GPIOB
#define MX_CAN2_RX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN2_RX_GPIO_Pin                     GPIO_PIN_5
#define MX_CAN2_RX_GPIO_AF                      GPIO_AF9_CAN2
#define MX_CAN2_RX_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PB6 */
#define MX_CAN2_TX_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_CAN2_TX_Pin                          PB6
#define MX_CAN2_TX_GPIOx                        GPIOB
#define MX_CAN2_TX_GPIO_PuPd                    GPIO_NOPULL
#define MX_CAN2_TX_GPIO_Pin                     GPIO_PIN_6
#define MX_CAN2_TX_GPIO_AF                      GPIO_AF9_CAN2
#define MX_CAN2_TX_GPIO_Mode                    GPIO_MODE_AF_PP

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA2_Stream3_IRQn */
#define MX_DMA2_Stream3_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream3_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream3_IRQn_Subriority         0

/* NVIC DMA2_Stream6_IRQn */
#define MX_DMA2_Stream6_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream6_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream6_IRQn_Subriority         0

/*-------------------------------- ETH        --------------------------------*/

#define MX_ETH                                  1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_ETH_REF_CLK_GPIO_Speed               GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_REF_CLK_Pin                      PA1
#define MX_ETH_REF_CLK_GPIOx                    GPIOA
#define MX_ETH_REF_CLK_GPIO_PuPd                GPIO_NOPULL
#define MX_ETH_REF_CLK_GPIO_Pin                 GPIO_PIN_1
#define MX_ETH_REF_CLK_GPIO_AF                  GPIO_AF11_ETH
#define MX_ETH_REF_CLK_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PA7 */
#define MX_ETH_CRS_DV_GPIO_Speed                GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_CRS_DV_Pin                       PA7
#define MX_ETH_CRS_DV_GPIOx                     GPIOA
#define MX_ETH_CRS_DV_GPIO_PuPd                 GPIO_NOPULL
#define MX_ETH_CRS_DV_GPIO_Pin                  GPIO_PIN_7
#define MX_ETH_CRS_DV_GPIO_AF                   GPIO_AF11_ETH
#define MX_ETH_CRS_DV_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PC4 */
#define MX_ETH_RXD0_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_RXD0_Pin                         PC4
#define MX_ETH_RXD0_GPIOx                       GPIOC
#define MX_ETH_RXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_RXD0_GPIO_Pin                    GPIO_PIN_4
#define MX_ETH_RXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD0_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC5 */
#define MX_ETH_RXD1_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_RXD1_Pin                         PC5
#define MX_ETH_RXD1_GPIOx                       GPIOC
#define MX_ETH_RXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_RXD1_GPIO_Pin                    GPIO_PIN_5
#define MX_ETH_RXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD1_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB11 */
#define MX_ETH_TX_EN_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_TX_EN_Pin                        PB11
#define MX_ETH_TX_EN_GPIOx                      GPIOB
#define MX_ETH_TX_EN_GPIO_PuPd                  GPIO_NOPULL
#define MX_ETH_TX_EN_GPIO_Pin                   GPIO_PIN_11
#define MX_ETH_TX_EN_GPIO_AF                    GPIO_AF11_ETH
#define MX_ETH_TX_EN_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA2 */
#define MX_ETH_MDIO_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_MDIO_Pin                         PA2
#define MX_ETH_MDIO_GPIOx                       GPIOA
#define MX_ETH_MDIO_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_MDIO_GPIO_Pin                    GPIO_PIN_2
#define MX_ETH_MDIO_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_MDIO_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB13 */
#define MX_ETH_TXD1_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_TXD1_Pin                         PB13
#define MX_ETH_TXD1_GPIOx                       GPIOB
#define MX_ETH_TXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_TXD1_GPIO_Pin                    GPIO_PIN_13
#define MX_ETH_TXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD1_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB12 */
#define MX_ETH_TXD0_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_TXD0_Pin                         PB12
#define MX_ETH_TXD0_GPIOx                       GPIOB
#define MX_ETH_TXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_TXD0_GPIO_Pin                    GPIO_PIN_12
#define MX_ETH_TXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD0_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC1 */
#define MX_ETH_MDC_GPIO_Speed                   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_ETH_MDC_Pin                          PC1
#define MX_ETH_MDC_GPIOx                        GPIOC
#define MX_ETH_MDC_GPIO_PuPd                    GPIO_NOPULL
#define MX_ETH_MDC_GPIO_Pin                     GPIO_PIN_1
#define MX_ETH_MDC_GPIO_AF                      GPIO_AF11_ETH
#define MX_ETH_MDC_GPIO_Mode                    GPIO_MODE_AF_PP

/* NVIC Configuration */

/* NVIC ETH_IRQn */
#define MX_ETH_IRQn_interruptPremptionPriority  0
#define MX_ETH_IRQn_PriorityGroup               NVIC_PRIORITYGROUP_4
#define MX_ETH_IRQn_Subriority                  0

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PB8 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_Pin                         PB8
#define MX_I2C1_SCL_GPIOx                       GPIOB
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_8
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB7 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Pin                         PB7
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_7
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- SDIO       --------------------------------*/

#define MX_SDIO                                 1

/* GPIO Configuration */

/* Pin PD2 */
#define MX_SDIO_CMD_Pin                         PD2
#define MX_SDIO_CMD_GPIOx                       GPIOD
#define MX_SDIO_CMD_GPIO_PuPd                   GPIO_NOPULL
#define MX_SDIO_CMD_GPIO_Speed_High_Default     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_CMD_GPIO_Pin                    GPIO_PIN_2
#define MX_SDIO_CMD_GPIO_AF                     GPIO_AF12_SDIO
#define MX_SDIO_CMD_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC12 */
#define MX_SDIO_CK_Pin                          PC12
#define MX_SDIO_CK_GPIOx                        GPIOC
#define MX_SDIO_CK_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_CK_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_CK_GPIO_Pin                     GPIO_PIN_12
#define MX_SDIO_CK_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_CK_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PC8 */
#define MX_SDIO_D0_Pin                          PC8
#define MX_SDIO_D0_GPIOx                        GPIOC
#define MX_SDIO_D0_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_D0_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D0_GPIO_Pin                     GPIO_PIN_8
#define MX_SDIO_D0_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_D0_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PC9 */
#define MX_SDIO_D1_Pin                          PC9
#define MX_SDIO_D1_GPIOx                        GPIOC
#define MX_SDIO_D1_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_D1_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D1_GPIO_Pin                     GPIO_PIN_9
#define MX_SDIO_D1_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_D1_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PC10 */
#define MX_SDIO_D2_Pin                          PC10
#define MX_SDIO_D2_GPIOx                        GPIOC
#define MX_SDIO_D2_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_D2_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D2_GPIO_Pin                     GPIO_PIN_10
#define MX_SDIO_D2_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_D2_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PC11 */
#define MX_SDIO_D3_Pin                          PC11
#define MX_SDIO_D3_GPIOx                        GPIOC
#define MX_SDIO_D3_GPIO_PuPd                    GPIO_NOPULL
#define MX_SDIO_D3_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDIO_D3_GPIO_Pin                     GPIO_PIN_11
#define MX_SDIO_D3_GPIO_AF                      GPIO_AF12_SDIO
#define MX_SDIO_D3_GPIO_Mode                    GPIO_MODE_AF_PP

/* DMA Configuration */

/* DMA SDIO_TX */
#define MX_SDIO_TX_DMA_MemBurst                 DMA_MBURST_INC4
#define MX_SDIO_TX_DMA_Instance                 DMA2_Stream6
#define MX_SDIO_TX_DMA_FIFOMode                 DMA_FIFOMODE_ENABLE
#define MX_SDIO_TX_DMA_Priority                 DMA_PRIORITY_MEDIUM
#define MX_SDIO_TX_DMA_Channel                  DMA_CHANNEL_4
#define MX_SDIO_TX_DMA_MemDataAlignment         DMA_MDATAALIGN_WORD
#define MX_SDIO_TX_DMA_Mode                     DMA_PFCTRL
#define MX_SDIO_TX_DMA_Direction                DMA_MEMORY_TO_PERIPH
#define MX_SDIO_TX_DMA_PeriphBurst              DMA_PBURST_INC4
#define MX_SDIO_TX_DMA_MemInc                   DMA_MINC_ENABLE
#define MX_SDIO_TX_DMA_IpInstance
#define MX_SDIO_TX_DMA_DMA_Handle
#define MX_SDIO_TX_DMA_PeriphDataAlignment      DMA_PDATAALIGN_WORD
#define MX_SDIO_TX_DMA_PeriphInc                DMA_PINC_DISABLE
#define MX_SDIO_TX_DMA_FIFOThreshold            DMA_FIFO_THRESHOLD_FULL

/* DMA SDIO_RX */
#define MX_SDIO_RX_DMA_MemBurst                 DMA_MBURST_INC4
#define MX_SDIO_RX_DMA_Instance                 DMA2_Stream3
#define MX_SDIO_RX_DMA_FIFOMode                 DMA_FIFOMODE_ENABLE
#define MX_SDIO_RX_DMA_Priority                 DMA_PRIORITY_MEDIUM
#define MX_SDIO_RX_DMA_Channel                  DMA_CHANNEL_4
#define MX_SDIO_RX_DMA_MemDataAlignment         DMA_MDATAALIGN_WORD
#define MX_SDIO_RX_DMA_Mode                     DMA_PFCTRL
#define MX_SDIO_RX_DMA_Direction                DMA_PERIPH_TO_MEMORY
#define MX_SDIO_RX_DMA_PeriphBurst              DMA_PBURST_INC4
#define MX_SDIO_RX_DMA_MemInc                   DMA_MINC_ENABLE
#define MX_SDIO_RX_DMA_IpInstance
#define MX_SDIO_RX_DMA_DMA_Handle
#define MX_SDIO_RX_DMA_PeriphDataAlignment      DMA_PDATAALIGN_WORD
#define MX_SDIO_RX_DMA_PeriphInc                DMA_PINC_DISABLE
#define MX_SDIO_RX_DMA_FIFOThreshold            DMA_FIFO_THRESHOLD_FULL

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS_SWDIO_Pin                   PA13

/* Pin PA14 */
#define MX_SYS_JTCK_SWCLK_Pin                   PA14

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA9 */
#define MX_USART1_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_TX_Pin                        PA9
#define MX_USART1_TX_GPIOx                      GPIOA
#define MX_USART1_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_9
#define MX_USART1_TX_GPIO_AF                    GPIO_AF7_USART1

/* Pin PA10 */
#define MX_USART1_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART1_RX_Pin                        PA10
#define MX_USART1_RX_GPIOx                      GPIOA
#define MX_USART1_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_10
#define MX_USART1_RX_GPIO_AF                    GPIO_AF7_USART1

/* NVIC Configuration */

/* NVIC USART1_IRQn */
#define MX_USART1_IRQn_interruptPremptionPriority 0
#define MX_USART1_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART1_IRQn_Subriority               0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PB2 */
#define MX_PB2_Pin                              PB2
#define MX_PB2_GPIOx                            GPIOB
#define MX_PB2_GPIO_PuPd                        GPIO_NOPULL
#define MX_EmergencyRear                        PB2
#define MX_PB2_GPIO_Pin                         GPIO_PIN_2
#define MX_PB2_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PE8 */
#define MX_PE8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE8_Pin                              PE8
#define MX_PE8_GPIOx                            GPIOE
#define MX_PE8_PinState                         GPIO_PIN_RESET
#define MX_PE8_GPIO_PuPd                        GPIO_NOPULL
#define MX_Motor1                               PE8
#define MX_PE8_GPIO_Pin                         GPIO_PIN_8
#define MX_PE8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE7 */
#define MX_PE7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE7_Pin                              PE7
#define MX_PE7_GPIOx                            GPIOE
#define MX_PE7_PinState                         GPIO_PIN_RESET
#define MX_PE7_GPIO_PuPd                        GPIO_NOPULL
#define MX_Motor0                               PE7
#define MX_PE7_GPIO_Pin                         GPIO_PIN_7
#define MX_PE7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA5 */
#define MX_PA5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA5_Pin                              PA5
#define MX_PA5_GPIOx                            GPIOA
#define MX_PA5_PinState                         GPIO_PIN_RESET
#define MX_PA5_GPIO_PuPd                        GPIO_NOPULL
#define MX_Relay                                PA5
#define MX_PA5_GPIO_Pin                         GPIO_PIN_5
#define MX_PA5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE9 */
#define MX_PE9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE9_Pin                              PE9
#define MX_PE9_GPIOx                            GPIOE
#define MX_PE9_PinState                         GPIO_PIN_RESET
#define MX_PE9_GPIO_PuPd                        GPIO_NOPULL
#define MX_Motor2                               PE9
#define MX_PE9_GPIO_Pin                         GPIO_PIN_9
#define MX_PE9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PE11 */
#define MX_PE11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE11_Pin                             PE11
#define MX_PE11_GPIOx                           GPIOE
#define MX_PE11_PinState                        GPIO_PIN_RESET
#define MX_PE11_GPIO_PuPd                       GPIO_NOPULL
#define MX_FrontEPS                             PE11
#define MX_PE11_GPIO_Pin                        GPIO_PIN_11
#define MX_PE11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE10 */
#define MX_PE10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE10_Pin                             PE10
#define MX_PE10_GPIOx                           GPIOE
#define MX_PE10_PinState                        GPIO_PIN_RESET
#define MX_PE10_GPIO_PuPd                       GPIO_NOPULL
#define MX_Motor3                               PE10
#define MX_PE10_GPIO_Pin                        GPIO_PIN_10
#define MX_PE10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE13 */
#define MX_PE13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE13_Pin                             PE13
#define MX_PE13_GPIOx                           GPIOE
#define MX_PE13_PinState                        GPIO_PIN_RESET
#define MX_PE13_GPIO_PuPd                       GPIO_NOPULL
#define MX_EBS                                  PE13
#define MX_PE13_GPIO_Pin                        GPIO_PIN_13
#define MX_PE13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE12 */
#define MX_PE12_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE12_Pin                             PE12
#define MX_PE12_GPIOx                           GPIOE
#define MX_PE12_PinState                        GPIO_PIN_RESET
#define MX_PE12_GPIO_PuPd                       GPIO_NOPULL
#define MX_RearEPS                              PE12
#define MX_PE12_GPIO_Pin                        GPIO_PIN_12
#define MX_PE12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE15 */
#define MX_PE15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE15_Pin                             PE15
#define MX_PE15_GPIOx                           GPIOE
#define MX_PE15_PinState                        GPIO_PIN_RESET
#define MX_PE15_GPIO_PuPd                       GPIO_NOPULL
#define MX_EPBS_REAR                            PE15
#define MX_PE15_GPIO_Pin                        GPIO_PIN_15
#define MX_PE15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE14 */
#define MX_PE14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PE14_Pin                             PE14
#define MX_PE14_GPIOx                           GPIOE
#define MX_PE14_PinState                        GPIO_PIN_RESET
#define MX_PE14_GPIO_PuPd                       GPIO_NOPULL
#define MX_EPBS_FRONT                           PE14
#define MX_PE14_GPIO_Pin                        GPIO_PIN_14
#define MX_PE14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PB1 */
#define MX_PB1_Pin                              PB1
#define MX_PB1_GPIOx                            GPIOB
#define MX_PB1_GPIO_PuPd                        GPIO_NOPULL
#define MX_EmergencyFront                       PB1
#define MX_PB1_GPIO_Pin                         GPIO_PIN_1
#define MX_PB1_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PB0 */
#define MX_PB0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB0_Pin                              PB0
#define MX_PB0_GPIOx                            GPIOB
#define MX_PB0_PinState                         GPIO_PIN_RESET
#define MX_PB0_GPIO_PuPd                        GPIO_NOPULL
#define MX_VCU                                  PB0
#define MX_PB0_GPIO_Pin                         GPIO_PIN_0
#define MX_PB0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

